on: [push]

name: Test in CI

jobs:
  build_and_test:
    name: Mipt Rust course homeworks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build and Run Tests
        run: cargo test -- -Z unstable-options --format json --report-time | cargo2junit > target/results.xml
        with:
          path: target/results.xml
