on: [push]

name: Test in CI

jobs:
  build_and_test:
    name: Homeworks – Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Test PyTest test import
        uses: ./
        with:
          check_name: Example Pytest Report
          report_paths: test_results/python/report.xml
          include_passed: true
          detailed_summary: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- -Z unstable-options --report-time