on: [push]

name: Test in CI

jobs:
  build_and_test:
    name: Mipt Rust course homeworks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml