on: [push]

name: Test in CI

jobs:
  build_and_test:
    name: Mipt Rust course homeworks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build and Run Tests
        run: cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: '*.xml'
          retention-days: 1