on: [push]

name: Test in CI

jobs:
  build_and_test:
    name: Rust course homeworks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Create file
        run: touch report.xml
      - name: ls
        run: ls -la
      - name: Build and Run Tests
        run: cargo test -- -Z unstable-options --format junit --report-time
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'